// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRvuE26WPWJKrKEUjVapw5zuaNTdxtLA8',
    appId: '1:145134409971:web:6d524901271bd0f9fc3f86',
    messagingSenderId: '145134409971',
    projectId: 'titanium-diode-379504',
    authDomain: 'titanium-diode-379504.firebaseapp.com',
    storageBucket: 'titanium-diode-379504.appspot.com',
    measurementId: 'G-YG1243W5JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnMURvRgorSK3jxZ_eqXxLMENtqou8fKI',
    appId: '1:145134409971:android:f0b7cca6da9d4783fc3f86',
    messagingSenderId: '145134409971',
    projectId: 'titanium-diode-379504',
    storageBucket: 'titanium-diode-379504.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhTQrwpFkmBP9u_NfR8-ZZLy0z9ofet9Q',
    appId: '1:145134409971:ios:7ef4738ea1a18b47fc3f86',
    messagingSenderId: '145134409971',
    projectId: 'titanium-diode-379504',
    storageBucket: 'titanium-diode-379504.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhTQrwpFkmBP9u_NfR8-ZZLy0z9ofet9Q',
    appId: '1:145134409971:ios:7ef4738ea1a18b47fc3f86',
    messagingSenderId: '145134409971',
    projectId: 'titanium-diode-379504',
    storageBucket: 'titanium-diode-379504.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRvuE26WPWJKrKEUjVapw5zuaNTdxtLA8',
    appId: '1:145134409971:web:aa4ccd868e798b52fc3f86',
    messagingSenderId: '145134409971',
    projectId: 'titanium-diode-379504',
    authDomain: 'titanium-diode-379504.firebaseapp.com',
    storageBucket: 'titanium-diode-379504.appspot.com',
    measurementId: 'G-VQHL6HSBQ2',
  );
}
